### ISSUE TITLE
shulkerBoxPreview cut off

### ISSUE THREAD

**Issue by srnyx** [maruohon/minihud#121]
The preview for shulker boxes are cut off in double chests or bigger.
_The blue bar at the top is the top of the window, the window is max size_
![image](https://user-images.githubusercontent.com/25808801/110179970-f7468780-7dd6-11eb-95a9-a361364cef6f.png)

**Comment by maruohon** [comment]
This should be fixed in the main development version of malilib, I fixed it somewhat recently. (it's not in any releases yet)

However I'm not sure how it will behave in this kind of case where the slots are at the very top of the window, but I believe it should just move the preview under the cursor in such a case, but I don't remember how it behaves in the left vs. right aspect..

**Comment by maruohon** [comment]
Let's keep this open for now so that I remember to check the new code with some modded larger inventories at some point.

**Comment by srnyx** [comment]
Safe to close?

**Comment by maruohon** [comment]
The previous comment still applies. I'll keep this open until the next releases are ready and become available.

**Comment by srnyx** [comment]
> The previous comment still applies. I'll keep this open until the next releases are ready and become available.

Alright, sounds good!
