### ISSUE TITLE
Bees counter not counting bees in a nest

### ISSUE THREAD

**Issue by ghost** [maruohon/minihud#124]
Bees counter always showing value 0, even if there are bees inside the nest. It would be really useful if that feature actually worked.

**Comment by maruohon** [comment]
It currently only works in single player, and on a server it will need a server-side mod to send the data to the client. That is planned for my Servux mod, but it doesn't have that support yet.

The vanilla server does not send block entity data to the clients that the client does not need for rendering purposes, so for the bee hives/nests it basically doesn't send any block entity data, as the honey level that is used for the model is part of the block state already. That's why it's not possible for this to work on all/vanilla servers, and it will need a mod to send the data.

**Comment by ChocolateLoverRaj** [comment]
@ItsMeNoodle It's working for me in singleplayer, so if the issue is with singleplayer then it doesn't always not-work.
