### ISSUE TITLE
Can't access Chunk Unload Bucket Overlay

### ISSUE THREAD

**Issue by rhettl** [maruohon/minihud#15]
Hello

I'd really like to see the Chunk Unload Buckets (saw it [here][1]), and I've found it in the code ([examples][2])

I'm assuming this has to do with the version I am using
![image](https://user-images.githubusercontent.com/1766765/63281418-845fd500-c261-11e9-87ac-ab9cb077b81f.png)

Is there a newer version I might use?
I've tried building myself but think my lack of experience with Java/Gradle Builds is hampering my efforts. 

Thank you for any information you can provide.

[1]: https://streamable.com/pwdu4
[2]: https://github.com/maruohon/minihud/search?q=unload&unscoped_q=unload

**Comment by vacla** [comment]
@rhettl in 1.14 it uses a ticket system and it unloads like i think almost directly.

**Comment by maruohon** [comment]
The unload bucket is only relevant for up to Minecraft 1.12.2.

In 1.13 they changed the HashSet used for the unloading, so that the unload order is totally different (gnembon has videos about that), and in 1.14 the entire chunk loading and handling got totally rewritten again.

So the old unload order basically has no meaning anymore in 1.14, even in 1.13.1+ the usefulness of it is questionable, and like I said, the order is totally different from 1.12 and before. So I just removed the entire unload order renderer starting from the 1.13.2 MiniHUD versions.

**Comment by rhettl** [comment]
Thank you very much, this heads off entire threads of investigation, haha. 

I will look for the Gnembon videos on the new unload system. Lots of work to run an ice farm from a distance.

**Comment by maruohon** [comment]
The gnembon videos are for 1.13.0 I believe. After that (in 1.13.1 and later) you can't really keep chunks loaded anymore without using the `/forceload` command, or in 1.14 using portal loading.

However, all of these are completely useless for an ice farm, as ice only freezes within the random ticked chunks around players anyway. You can use the Random Tick Range overlay in MiniHUD to see that range.

**Comment by rhettl** [comment]
Ahh, I will look into the Random Tick Range overlay, just to see what it does, but I guess AFK is going to be the only way to do it then. 

I appreciate all the information you've provided and for making these mods and making them so relatively easy to setup and use.
