### ISSUE TITLE
Structure overlay doesn't work

### ISSUE THREAD

**Issue by NingyuanBi** [maruohon/minihud#150]
Dear maruohon

Structure overlay doesn't work on my client while others are working. I am sure I have input the seed already.

My game version is 1.16.5

**Comment by maruohon** [comment]
The structure bounding boxes don't work based on the seed alone. (This is intentional, since it's not possible to account for older world generator versions, or custom or modified structures.) Only the slime chunks use the seed.

For structure bounding boxes on a server you need a server-side mod to send the actual structure data. That mod in most cases would be [Servux](https://www.curseforge.com/minecraft/mc-mods/servux).

**Comment by NingyuanBi** [comment]
> The structure bounding boxes don't work based on the seed alone. (This is intentional, since it's not possible to account for older world generator versions, or custom or modified structures.) Only the slime chunks use the seed.
> 
> 
> 
> For structure bounding boxes on a server you need a server-side mod to send the actual structure data. That mod in most cases would be [Servux](https://www.curseforge.com/minecraft/mc-mods/servux).

Oh thx for your reply. It seems that I knew what's wrong with that. Thank you again!

**Comment by ExSalty0** [comment]
> The structure bounding boxes don't work based on the seed alone. (This is intentional, since it's not possible to account for older world generator versions, or custom or modified structures.) Only the slime chunks use the seed.
> 
> For structure bounding boxes on a server you need a server-side mod to send the actual structure data. That mod in most cases would be [Servux](https://www.curseforge.com/minecraft/mc-mods/servux).

Even with servux it isnt working you have any idea why?

**Comment by maruohon** [comment]
@ExSalty0 Is the server running the same MC version as your client? Are there any version conversion mods or proxies being used?

Enable the `debugMessages` option in the Generic config category, and then use the `overlayStructureMainToggle` **hotkey** to toggle off and on the structure renderer, and then look in the game console/log. You should see a few messages about toggling the structure renderer, and whether Servux responds and sends structure data from the server.

**Comment by LeMagiD** [comment]
Hello @maruohon, it's not rendering for me. Both my client and my server are on version 1.19.2, i've used the /seed command, servux is on the server and i get the following log when using the `overlayStructureMainToggle` hotkey :

![grafik](https://github.com/user-attachments/assets/58e1e895-f403-43b0-8e91-0a514baf47c0)
i'm renting the server so i'm not sure about any version conversion mods or proxies, but i do have the following mods installed on the server, aswell as on the client (minus the servux mod). Could any of these maybe be a problem? It works on singelplayer tho so i don't think that it's because of one of the other mods
![grafik2](https://github.com/user-attachments/assets/3d28691f-67e6-4ef5-8186-63e181580a6f)

**Comment by maruohon** [comment]
@LeMagiD If you have the `debugMessages` option enabled in MiniHUD, then you should get more output than that when you toggle the `overlayStructureMainToggle` option.

You should see something like this if the communication with Servux actually works:
```
[13:18:36] [Render thread/INFO]: DataStorage#registerStructureChannel(): Servux
[13:18:36] [Render thread/INFO]: DataStorage#registerStructureChannel(): Carpet
[13:18:36] [Render thread/INFO]: StructurePacketHandlerServux#onPacketReceived(): 1
[13:18:36] [Render thread/INFO]: DataStorage#setIsServuxServer()
[13:18:36] [Render thread/INFO]: StructurePacketHandlerServux#onPacketReceived(): 2
[13:18:36] [Render thread/INFO]: DataStorage#addOrUpdateStructuresFromServer(): start
[13:18:36] [Render thread/INFO]: DataStorage#addOrUpdateStructuresFromServer(): count: 2
```

If you don't get this, then something must be dropping the custom payload packets that MiniHUD or Servux is sending. From the mods on that list, I don't know what "Bad Packets" is/does, that's the only possibility from that list in my mind, the other mods shouldn't be related to that (unless they have some buggy implementations with packets).

You can/should remove the client-side mods from the server. They either don't do anything there, or in some cases they might even cause issues or crash the server, although I imagine that's probably pretty rare (and would be due to buggy implementation). From your list above remove at least Litematica, malilib, MiniHUD, Mod Menu and Sodium from the server. From some of the other ones I'm not sure if they have some server-side functionality in the same mod... I'm skeptical about freecam and MouseTweaks, and more unsure about InventorySorter and JEI and WHIT. The last three might need to be there for full functionality. Check the mod description/documentation for all the last five mods mentioned, whether they should also be on the server.
