### ISSUE TITLE
infoLightLevel + tickwarping freeze

### ISSUE THREAD

**Issue by xenallio** [maruohon/minihud#17]
Tickwarping while having infoLightLevel turned on freeze the game until tickwarping is finished. I did test after turning off other infos and removing all uneeded mods. Tried tickwarp from quickcarpet and fabriccarpet

1.14.4 + latest version of minihud, malilib, fabric + fabricapi0.3.1.208

**Comment by maruohon** [comment]
I did briefly profile this issue already due to previous reports, and it looks like any of the info types that in single player access a server chunk directly freeze the game. I need to see if I can access the chunks in a way that won't cause that freeze, or if I just have to get rid of that access completely. I think I might be able to use the same code for that chunk access that vanilla uses in some of its F3 screen lines.

**Comment by maruohon** [comment]
This should be fixed in the latest builds, starting from the `2019-10-07` build. (Fixed in 39bc8a75e1 ).
