### ISSUE TITLE
[1.17.1] Shape renderer causes massive frame drops

### ISSUE THREAD

**Issue by utbrott** [maruohon/minihud#172]
Observed on theGlotzerify's stream. Active shape renderer spheres, not loaded, far from player, were causing Glotz to lose over 100 fps (from stable 144fps to even as low as 24fps) in certain spots while on the server with active shapes. With shapes disabled frames got back to normal.

**Comment by maruohon** [comment]
Based on the stream VoD, I tried one despawn sphere in the same place (the first one glotz had, since the coordinates of that were briefly visible) and having the player in the exact same place where glotz was. Enabling the shape renderer definitely had an effect, but in my case it wasn't nearly as severe. I went from something like 400 fps to 120 fps while having the F3 screen with the profiler chart open. (without the F3 screen and without the shape renderer I was at around 800-900 FPS in that place.) The only thing the vanilla profiler pie chart was showing was that the `updateDisplay` section started growing when I toggled on the shape renderer. I'm not entirely sure what that means in this case...
