### ISSUE TITLE
Mini-hud block braking 

### ISSUE THREAD

**Issue by Dondyblondie2** [maruohon/minihud#173]
So I installed mini hud today and then I put it in my mods folder and I get on and open the setting for it and I put the day counter and then I go to brake a block and I can’t it just shows and disappears the fps where the day counter is and I can only brake blocks when I shift or jump. Plz help me out

**Comment by maruohon** [comment]
Did you accidentally bind something (like the FPS info line toggle) to left click? It would then eat the left click event and cancel further processing of left clicks. The default toggle hotkey setting don't allow extra keys to be pressed, that's why for example sneaking would prevent the hotkey from working and the key event from being eaten.

**Comment by Dondyblondie2** [comment]
> Did you accidentally bind something (like the FPS info line toggle) to left click? It would then eat the left click event and cancel further processing of left clicks. The default toggle hotkey setting don't allow extra keys to be pressed, that's why for example sneaking would prevent the hotkey from working and the key event from being eaten.

Thanks it worked
