### ISSUE TITLE
nothing is rendering for me (spigot server or singleplayer and fast render off)

### ISSUE THREAD

**Issue by MrChockablox** [maruohon/minihud#19]
nothing will render for me on a server or singleplayer, like the slime chunks, structures boxes or despawn sphere. the info in the corner works fine.

i've tried reinstalling the mod and its library mod, setting hot keys and turing fast render on and off multiple times and messing around with the margins and colors ive checked its up to date and it still won't render anything

and yes i am using 1.14.4 fabric

plz help, TIA

**Comment by maruohon** [comment]
Did you set the hotkeys for the renderers in the Renderer Hotkeys category? The Slime Chunk overlay, the Structure Bounding boxes renderer, and the shape renderer (for the Despawn Sphere shape) all currently need to be toggled on using hotkeys in the Renderer Hotkeys category.

And Structure Bounding boxes won't work on a Spigot server, because there needs to be a mod on the server sending the structure bounding box data, and currently the only mod in 1.14+ that does it in a format that MiniHUD knows about, is the QuickCarpet mod.

**Comment by vacla** [comment]
@MrChockablox for all the following you need rendering enabled
for slime chunks you need to do `/seed` or `seed <seed>`
for structure boxes on a server you need to have quickcarpet, won't work on spigot, on single player you need to enable structures and also type that you want
for despawn sphere you need to have added the despawn sphere and enable `shapeRendere`

**Comment by MrChockablox** [comment]
finally, i can dig a proper perimeter for my quad slime farm. thanks for the help.
