### ISSUE TITLE
shulkerBoxPreview

### ISSUE THREAD

**Issue by Flus1234** [maruohon/minihud#193]
I use the shulkerBoxPreview option and the display window is displayed behind the list from the mod RoughlyEnoughItems so nothing is visible (translated with the help of Google translator).

![1232](https://user-images.githubusercontent.com/61036027/147967595-ab2913c6-204e-425b-bb73-c4dcc3a886a5.png)

**Comment by fooeyround** [comment]
Ofc it’s an issue with layers but idk why the 2 layers of the thingy are not bunched maybe cause the item layer in the gui? Like in some cases with. Some formats with mods and such it will do this because all of rei is item layer and the background is how it is… hmmm you can also disable rei rendering when you don’t need it if you want but yes bizzar and can bot happen for some people.

**Comment by maruohon** [comment]
See if this is fixed by the new releases for 1.18.1 that were released today.

**Comment by Flus1234** [comment]
Now the items are in the foreground, and the frame itself is behind REI
![2022-01-22_10 31 22](https://user-images.githubusercontent.com/61036027/150626566-1fd3b6fc-ca0c-4d39-bef6-211e4ba73043.png)
I know that I can turn off the display of the REI, but I would like everything to work without additional toggles.

**Comment by maruohon** [comment]
This should now be fixed in malilib 0.11.5: https://www.curseforge.com/minecraft/mc-mods/malilib/files/3619948

**Comment by Flus1234** [comment]
Now everything looks great. Thank you very much for your work.
