### ISSUE TITLE
I need so much to expand custom sphere to 450 radius block

### ISSUE THREAD

**Issue by Xtanley** [maruohon/minihud#195]
Can you unlock limit of custom sphere radius to 512, i know the risk of performance but i need so much this feature to build a wonderful skyscraper.

Congratulations in any case for the mod and if you can't thanks anyway.

**Comment by maruohon** [comment]
The just released 1.18.1 version now bumps the max radius to 1024 blocks.

It also has some optimizations and improvements to the shapes. In particular if you don't need a full sphere (which you shouldn't since it would even go way above the world build height), then I'd recommend doing it such that you add the shape, keep it disabled, go and configure it, and set the render layers to Single Layer or Layer Range or whichever you need, possibly also enable the new Combine Quads option, and then toggle the shape on. At least Circles or otherwise "thin" sections of that large spheres should be fine now.

**Comment by Xtanley** [comment]
Fantastic, great work! Thankyou very much :)
