### ISSUE TITLE
mainRenderingToggle does not have a keybind in the config file 1.18.1

### ISSUE THREAD

**Issue by LOLboy199** [maruohon/minihud#205]
I'm not sure how new the 'main rendering toggle' in the info lines tab is, but this is my first time encountering an issue with it.
You can rebind the hotkey in-game, which can be changed from the default "H" key to whatever, but once the game is reloaded it will always reset to "H". 

I'm pretty sure the issue is that it does not have a "keys" line in the config file code. For example:
"openConfigGui": {
   "keys": "H,C",
... etc. 

I've looked through my original config file like 3 or 4 times and didn't find it. I deleted it and let the game create a new file and couldn't find it. 

The only option it has in the config file is:
"mainRenderingToggle": true,

Maybe I'm missing something, but any help would be appreciated. Thank you in advance.

**Comment by LOLboy199** [comment]
Also it looks like 'mainRenderingToggle' is an option in both the Generic tab and the Info Lines tab, not sure if that was intentional or not.

**Comment by maruohon** [comment]
Looks like the config option type it uses (`ConfigBooleanHotkeyed` from malilib) doesn't actually serialize and de-serialize the hotkey part at all atm... whoops. That config type was before now only used in Tweakeroo's Disable/Yeet options, and those use a "manual" wrapper in the config class that writes the boolean and hotkey parts into separate JSON objects in the config file, so I never ran into this issue before now. I'll need to release a bug fix for malilib to fix this.

And yes I intentionally added the main rendering toggle to all the categories (on the config screen only) that "have stuff that it toggles off". Similarly the `overlayStructuresMainToggle` is both in Renderers where it actually lives in the config, and on the top of Structures category, since it controls all of those. It has been a fairly common issue for new users that they don't know to turn it on since it was buried in a separate category.

**Comment by LOLboy199** [comment]
I'm so sorry but my pea-brain barely understands code. lol I wish I knew more so I could help. But yes that solution sounds very smart and correct I agree!

And I see. Very intuitive.

**Comment by LOLboy199** [comment]
Fixed with latest releases of MiniHud and Malilb!
