### ISSUE TITLE
option to have the F3 crosshair

### ISSUE THREAD

**Issue by Un1q32** [maruohon/minihud#225]
When using F3, the crosshair turns into a 3 colored lines that align with the xyz axis.  It would be nice to have the option to have that when using minihud as well.

**Comment by maruohon** [comment]
This is one of the features in the Tweakeroo mod.

**Comment by Un1q32** [comment]
> This is one of the features in the Tweakeroo mod.

still, it would be nice to not have to install a separate mod for this one feature

**Comment by maruohon** [comment]
But you could literally say that about any feature in any mod.

"I'm using MiniHUD, but it would be nice if the Item Scroller Alt + click to move all identical items was also in this mod so I don't have to install Item Scroller" or "would be nice if I could also view schematics with MiniHUD".

Now the F3 cursor feature is kinda on the MiniHUD "show info and overlays" territory, but on the other hand the implementation of that feature needs to override vanilla code in that one place, and in general I'd like to keep MiniHUD as "light" as possible on the use of Mixins for better compatibility and less potential issues. It already has quite a few of them anyway to be able to update to all the things it needs to react to, or to get all the information it needs to get to display various things. But I'd like to avoid turning this mod into the same type of tweak mod that Tweakeroo is, by changing vanilla behavior, instead of just showing extra information like it does currently.
