### ISSUE TITLE
Crash when opening Fabric MiniHud 1.18.2

### ISSUE THREAD

**Issue by goatsplusone** [maruohon/minihud#241]
There is an instant crash when install MinHud for Fabric 1.18.2 (Exit Code: 1)

**Comment by maruohon** [comment]
Without a crash log I can't say anything other than "did you also install malilib, and are both mods for the correct MC version"?

**Comment by goatsplusone** [comment]
Yes I did install malilib, and yes both are for 1.18.2 but when i remove MiniHud Fabric boots as normal
![image](https://user-images.githubusercontent.com/106512038/171071401-f26cc24a-c4fb-4c7d-8f9d-7b10995e75ba.png)

**Comment by maruohon** [comment]
This short crash message doesn't tell me anything at all unfortunately. Look in the `.minecraft/crash-reports/` directory, if you have a file corresponding to the crash timestamp. Otherwise look in `.minecraft/logs/latest.log` and post that to something like pastebin or hastebin and post the link here.

**Comment by maruohon** [comment]
I'm closing this as stale. If you still have the issue, feel free to re-open this.
