### ISSUE TITLE
Bounding Boxes Not Working In 1.18.2

### ISSUE THREAD

**Issue by Aqawma** [maruohon/minihud#243]
Bounding boxes are now rendering in 1.18.2 in multiplayer(I have servux) and singleplayer. Is this a known issue or just me and if it is known are there any fixes?

**Comment by maruohon** [comment]
About half of the bounding box types are currently broken in the `0.22.0` version of MiniHUD for 1.18.2. They changed/renamed many of the bounding boxes in 1.18.2, and I missed that in that first 1.18.2 update of the mod.

The bounding box types and their configuration is currently hard coded in the mod, so I always need to ad any new definitions if they add new structure types. That's why I'd like to rewrite that stuff so that it would automatically support any structure that exist in the game. But that means a somewhat notable rewrite of how the structure bounding box configs ad stuff works, and I haven't had much time for modding in general lately.

However if you don't see any structures at all, then there might be some other issue. Do you have the MiniHUD main rendering toggle on (`H`) and the `overlayStructureMainToggle` on in addition to the structure types themselves? Also using shaders currently most likely breaks all overlay rendering.

**Comment by maruohon** [comment]
The structure bounding boxes were fixed in the new 1.18.2 version (0.22.1), and it's also fixed in the "official" 1.19+ versions that were released a few days ago.
