### ISSUE TITLE
no light level for 1 snow layer

### ISSUE THREAD

**Issue by drwoops** [maruohon/minihud#257]
a single layer of snow does not prevent mob spawning, but the light level renderer does not render anything for them.

**Comment by maruohon** [comment]
It does render, it just renders inside the block.
![2022-08-09_18 54 41](https://user-images.githubusercontent.com/2331050/183700245-6019ae7d-4a57-43ab-9b3a-96226afb44bc.png)

There is an option in Generic -> `lightLevelAutoHeight` that makes it render on top of the block's top surface.
It's not enabled by default since it changes behavior from the old defaults, and causes sort of confusing things like rendering the light level on top of basically all blocks, like all heights of snow layers, on top of slabs etc.
![2022-08-09_18 57 41](https://user-images.githubusercontent.com/2331050/183701102-6d228de4-b070-4745-91d2-a64255fb3d66.png)


And to "fix" that, there is another option `lightLevelCollisionCheck` which causes the light level to be skipped for blocks that have a collision box that would prevent spawning. That option also has at least a minor/small(?) performance impact for updating the overlay.
![2022-08-09_18 58 02](https://user-images.githubusercontent.com/2331050/183701136-32338108-7c11-4125-8bf5-90482830ae9b.png)

**Comment by Wolkenfarmer** [comment]
I would prefer to have that as default, but great that you already implemented fixes for this edge case :D
