### ISSUE TITLE
Crash on going to controls screen

### ISSUE THREAD

**Issue by Zygus42** [maruohon/minihud#3]
minihud-1.12.0-0.10.0
forge-1.12-14.21.0.2322-installer-win
no other mods

When you try and go to the Options/Controls screen, you get the following crash:
[crash-2017-06-12_10.32.47-client.txt](https://github.com/maruohon/minihud/files/1066986/crash-2017-06-12_10.32.47-client.txt)

**Comment by maruohon** [comment]
This seems to be due to a change in the KeyBinding class, and it will currently crash with ANY mod that adds it's keybindings to a custom category, instead of using one of the existing vanilla ones. So this will require a Forge change, and depending on how it will be implemented, a mod update may or may not be needed...

**Comment by maruohon** [comment]
This has now been fixed in Forge 2324 or newer.
