### ISSUE TITLE
Freecam moving random tick range overlay

### ISSUE THREAD

**Issue by jones-josh** [maruohon/minihud#300]
When using freecam (freecam mod and the freecam from tweakeroo are the ones I have tested) the overlay from overlayRandomTicksPlayer moves with the freecam instead of remaining centered on the player. 

Confirmed with experimentation that the random ticks were still centered around the player and NOT from the free cam position - the renderer is not reflecting the true random tick range, tested using 0.25.0 (minecraft ver 1.19.3).

A similar working feature is the pseudo spawn chunks. These remain in position around the player during free cam.

**Comment by maruohon** [comment]
This is actually done on purpose, so that you can preview things from the free camera perspective while looking for a suitable center location.

I know there are different situations where one or the other behavior would be preferable, so my intention is to add some kind of config option to allow selecting the behavior. Just not sure yet how that will look like, since there are several different uses of the camera vs. player position in the mods (rendered overlays, info line coordinates, Litematica schematic block info lines, block info overlay, tool usage etc.), and I probably don't want to add separate options for each of these.

**Comment by jones-josh** [comment]
That is a very obvious use case I did not consider. Having not used litematica before (and I assume there are other mods you similar want to maintain good interoperability with) and not being too familiar with this project's codebase, I wouldn't be comfortable with implementing the feature as you've described.

I will continue to use my branch as it is better suited to my use and look forward to your implementation.
