### ISSUE TITLE
World seed unknown 

### ISSUE THREAD

**Issue by Fluffybanana7** [maruohon/minihud#34]
When on servers Mini Hud can not find the world seed I think a good fix for this would be to add a seed input in the general settings

**Comment by maruohon** [comment]
I don't think it would be a good idea to include it in the normal settings, since then it would be set to the same value in all worlds.

Currently you can set the seed in two ways:
* If you have the permission, you can just run the vanilla `/seed` command and MiniHUD will grab the seed from the chat message
* If you don't have the permission to run `/seed`, but you know the seed, you can input it for MiniHUD with a normal chat message in the format `minihud-seed 12345`. MiniHUD will grab it from the message and not send the message.
