### ISSUE TITLE
Shape Manager only adding despawn spheres

### ISSUE THREAD

**Issue by gnp** [maruohon/minihud#36]
I'm using 1.15.2 and this version: minihud-fabric-1.15.2-0.19.0-dev.20200121.203515.jar

I wanted to set a sphere of my own parameters in the shapes.

There was no way to set the shape type before clicking "Add shape". The menu just to the left looks like it is a menu for choosing info bits to put on the HUD itself. Seems like that menu should be allowing me to pick what type of shape I want to add, then hopefully I could pick a "manual sphere" option and set the origin and radius in config page.

I've uploaded a screenshot:

![2020-03-17_11 41 53](https://user-images.githubusercontent.com/62487/76891068-a0eadc80-6845-11ea-8163-f5f920352903.png)

**Comment by maruohon** [comment]
The current 1.13.2 - 1.15.2 versions of MiniHUD still only have the Despawn Sphere shape. That dropdown was basically just forgotten in when I was using it to test the dropdown widget itself while implementing it for malilib.

In the 1.12.x versions there are a few more shapes now, including a generic Sphere. I did a temporary port from the 1.12.x codebase to the 1.16 snapshots a little while ago. Since there were no changes affecting MiniHUD in the first 1.16 snapshots, you can actually use the 20w09a version of MiniHUD on 1.15.x as well. It's available here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16-snapshot-20w09a

There are some glitches and bugs in some of the GUIs at least, and I don't know if the structure bounding boxes work properly for example. I didn't bother fixing everything properly, because it's just a temporary port, and I had to copy paste a bunch of stuff temporarily from malilib to MiniHUD directly to fix things that have changed in malilib in 1.12.x since last June, which is what the 1.13.2+ versions of the mods are currently based on. A new proper port from 1.12 to 1.13.2 to 1.14.4 to 1.15.2 to 1.16.x will happen at some point later when I finish some things in 1.12 first.
