### ISSUE TITLE
Certain Overlays not working

### ISSUE THREAD

**Issue by MysticPengu** [maruohon/minihud#46]
Only some overlays don't work for me. I've tried both the forge and fabric versions and neither work. The Slime chunk overlay does work but the structure overlay doesn't and neither does the despawn sphere

**Comment by vacla** [comment]
for structure overlay you need to toggle `overlayStructureMainToggle` and works only in singleplayer or quickcarpet server, and for despawn sphere you need to toggle `shapeRenderer` and have minihud rendering also enabled

**Comment by maruohon** [comment]
All of them need to be turned on, currently using a hotkey you set in the Renderer Hotkeys category. So for example for the Structures you should enable the types you want to see, and then set a hotkey for `overlayStructureMainToggle`, and for any shapes in the Shapes category you use the `shapeRenderer` hotkey. There will be direct toggle options as well in the future so you don't need all the hotkeys...

**Comment by MysticPengu** [comment]
I have got the structure renderer on with a hot key, and a hot key assigned to the witch hut but it doesn’t work when I press the assigned hot key, but it does say the structure renderer is on when I press that hotkey. When I turn the witch hut renderer on. I’ve used this mod on servers in the past and it works fine, I’m not sure if they’ve changed it but the slime chunk renderer still works.

**Comment by maruohon** [comment]
The structure bounding boxes need the server to send the data. I think there was (or is?) a bug where if you joined a single player world first, and then switched to a server, it would not properly clear the structure data. Is this potentially what you saw before? Otherwise the server must have been running the QuickCarpet mod to send the structure data for MiniHUD.

So currently the server must run either the Servux mod (which is my new server-side mod for sending data to my client mods), or the QuickCarpet mod to be able to send the structure data. (FabricCarpet does not send the data, and neither does CarpetExtra.) The Slime chunks on the other hand work entirely based on the world seed.

If the server is running Fabric, then (if it's yours or you can request a mod to be added) you can use Servux to get the bounding boxes working with MiniHUD: https://masa.dy.fi/tmp/minecraft/mods/servux/servux-fabric-1.14.4-0.1.0.jar
This version will work on both 1.14.4 and 1.15.2, but not on 1.16 snapshots.
You will also need a new MiniHUD version to support Servux. I'll upload them to CurseForge now (or you can get them from my server: https://masa.dy.fi/mcmods/client_mods/).

**Comment by MysticPengu** [comment]
I have got the structure renderer on with a hot key, and a hot key assigned to the witch hut but it doesn’t work when I press the assigned hot key, but it does say the structure renderer is on when I press that hotkey. When I turn the witch hit on

**Comment by MysticPengu** [comment]
The servers only a little smp server hosted on Minehut. I can’t find those mods on their mod downloads. I’m just using these mods to get an advantage.

**Comment by vacla** [comment]
You won't be able to get the structure overlays working then.
