### ISSUE TITLE
Game crashed after toggling light overlay

### ISSUE THREAD

**Issue by ardenmorsolias** [maruohon/minihud#69]
used the hotkey to toggle light overlay turning it on, game crashed
[crash-2020-07-17_22.44.36-client.txt](https://github.com/maruohon/minihud/files/4940996/crash-2020-07-17_22.44.36-client.txt)
game functions as normal until i try to join a server at which point it crashes
after turning off light overlay before joining the server, joining the server still causes game to crash
[crash-2020-07-17_22.48.09-client.txt](https://github.com/maruohon/minihud/files/4940992/crash-2020-07-17_22.48.09-client.txt)

**Comment by ardenmorsolias** [comment]
UPDATE: attempted to join a normal singleplayer world, game crashed

[crash-2020-07-17_22.57.52-server.txt](https://github.com/maruohon/minihud/files/4940995/crash-2020-07-17_22.57.52-server.txt)

**Comment by maruohon** [comment]
That first crash is fixed in the latest MiniHUD build (here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.1). I need to upload that to CurseForge as well...

That last crash shouldn't be related to MiniHUD at all. Not sure what exactly causes it, it might be between xaero's minimap and Lithium maybe?
