### ISSUE TITLE
infoBiome doesn't show since updating to 1.16.2

### ISSUE THREAD

**Issue by kattmat89** [maruohon/minihud#79]
As title suggests. infoBiome doesn't show, even though info toggle is set to "true", since updating to 1.16.2.

**Comment by maruohon** [comment]
This is because the Biome stuff was majorly rewritten in 1.16.2, and I couldn't immediately find a way to get a human readable name for it anymore, so the code for this info line is just commented out currently. You can still use the registry name variant of it to get the name the biome is registered as to the game registry. I'll take another look at some point to see if there is still some place to get the old human readable name from.
